# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
a1

array([1, 2, 3])

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.ndim

((3,), 3, 1)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim

((2, 3), 6, 2)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.ndim

((2, 3, 3), 18, 3)

In [8]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [10]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[5, 3],
       [5, 5],
       [4, 5],
       [3, 6],
       [5, 9],
       [7, 2],
       [2, 8]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.74485535, 0.85664073, 0.21220848, 0.21825788, 0.61142016],
       [0.40985931, 0.00512449, 0.10842727, 0.45895998, 0.68531964],
       [0.74023667, 0.82905467, 0.53821634, 0.61238328, 0.38167244]])

In [27]:
# Set the random seed to 42
np.random.seed(42)
np.random.randint(10,size=(4,6))

# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_array = np.random.randint(1,10,size=(3,7))
rand_array
# Find the unique numbers in the array you just created


array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3],
       [1, 3, 5, 3, 1, 5, 7]])

In [37]:
# Find the 0'th index of the latest array you created
rand_array[0]

array([9, 7, 9, 8, 2, 1, 7])

In [42]:
# Get the first 2 values of the first 2 rows of the latest array
rand_array[:2, :2]

array([[9, 7],
       [7, 8]])

In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_array2 = np.random.randint(10,size=(3,5))
ones_array = np.ones((3,5))

In [49]:
# Add the two arrays together
rand_array2 + ones_array

array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

In [50]:
# Create another array of ones of shape (5, 3)
ones_array2 = np.ones((5,3))

In [51]:
# Try add the array of ones and the other most recent array together
ones_array + ones_array2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [56]:
ones_array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
# Create another array of ones of shape (3, 5)
ones_array3 = np.ones((3,5))
ones_array3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
# Subtract the new array of ones from the other most recent array
ones_array3.T - ones_array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
ones_array3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Multiply the ones array with the latest array
ones*ones_array3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
# Take the latest array to the power of 2 using '**'
ones_array3**2
rand_array**2
np.sqrt(rand_array)

array([[3.        , 2.64575131, 3.        , 2.82842712, 1.41421356,
        1.        , 2.64575131],
       [2.64575131, 2.82842712, 2.23606798, 1.73205081, 2.82842712,
        2.44948974, 1.73205081],
       [1.        , 1.73205081, 2.23606798, 1.73205081, 1.        ,
        2.23606798, 2.64575131]])

In [69]:
# Do the same thing with np.square()
np.sqrt(rand_array2)

array([[2.23606798, 1.        , 3.        , 2.82842712, 2.        ],
       [2.23606798, 1.73205081, 3.        , 2.44948974, 2.82842712],
       [2.44948974, 0.        , 0.        , 2.82842712, 2.82842712]])

In [76]:
rand_array2

array([[5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8],
       [6, 0, 0, 8, 8]])

In [71]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array2)

5.333333333333333

In [74]:
# Find the maximum of the latest array using np.max()
np.max(rand_array2)

9

In [75]:
# Find the minimum of the latest array using np.min()
np.min(rand_array2)

0

In [77]:
# Find the standard deviation of the latest array
np.std(rand_array2)

3.0477678535099892

In [78]:
# Find the variance of the latest array
np.var(rand_array2)

9.288888888888888

In [79]:
# Reshape the latest array to (3, 5, 1)
rand_array2

array([[5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8],
       [6, 0, 0, 8, 8]])

In [81]:
rand_array2.shape

(3, 5)

In [82]:
rand_array2.reshape(3,5,1)

array([[[5],
        [1],
        [9],
        [8],
        [4]],

       [[5],
        [3],
        [9],
        [6],
        [8]],

       [[6],
        [0],
        [0],
        [8],
        [8]]])

In [83]:
# Transpose the latest array
rand_array2.T

array([[5, 5, 6],
       [1, 3, 0],
       [9, 9, 0],
       [8, 6, 8],
       [4, 8, 8]])

What does the transpose do?

In [85]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array3 = np.random.randint(10,size=(3,3))
rand_array4 = np.random.randint(10,size=(3,2))

In [86]:
rand_array3

array([[2, 9, 7],
       [5, 7, 8],
       [3, 0, 0]])

In [87]:
rand_array4

array([[9, 3],
       [6, 1],
       [2, 0]])

In [88]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array3,rand_array4)

array([[ 86,  15],
       [103,  22],
       [ 27,   9]])

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_array5 = np.random.randint(10,size=(4,3))
rand_array6 = np.random.randint(10,size=(4,3))

In [94]:
rand_array5

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [95]:
rand_array6

array([[5, 6, 3],
       [6, 7, 0],
       [5, 7, 4],
       [3, 1, 5]])

In [96]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array5,rand_array6.T)

array([[ 9,  7, 11,  6],
       [73, 72, 83, 41],
       [ 6,  0,  8, 10],
       [56, 34, 69, 52]])

It doesn't work. How would you fix it?

In [36]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [37]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [99]:
rand_array5

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [98]:
rand_array6

array([[5, 6, 3],
       [6, 7, 0],
       [5, 7, 4],
       [3, 1, 5]])

In [97]:
# Compare the two arrays with '>'
rand_array5 > rand_array6

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
rand_array5 >= rand_array6

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True,  True]])

In [113]:
# Find which elements of the first array are greater than 7
rand_array3

array([[2, 9, 7],
       [5, 7, 8],
       [3, 0, 0]])

In [116]:
a1

array([1, 2, 3])

In [117]:
a1 > rand_array3

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [118]:
# Which parts of each array are equal? (try using '==')
a1 == rand_array3

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [119]:
rand_array5 == rand_array6

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [120]:
ones == ones_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [137]:
rand_array5

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [139]:
rand_array5 == np.sort(rand_array5)

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [138]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_array5)

array([[0, 1, 1],
       [4, 5, 6],
       [0, 0, 2],
       [1, 4, 9]])

In [140]:
rand_array6 == np.sort(rand_array6)
# rand_array6 was is already sorted

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [147]:
# Sort the indexes of one of the arrays you just created
rand_array7 = np.random.randint(100,size=(10,9))
rand_array7

array([[23, 92, 45, 52, 94, 98, 59, 96, 62],
       [84, 31, 86, 32, 66, 17, 24, 94, 53],
       [57, 66, 45, 23, 31, 46, 85, 22, 65],
       [26,  1, 89, 16, 32,  8, 42, 47, 38],
       [92, 41, 25, 98, 49, 24, 23, 12, 59],
       [ 6, 56, 35, 44, 19, 64,  7, 15, 13],
       [75, 86, 14, 91, 97, 65, 31, 86, 62],
       [85, 50, 24, 57, 62, 61, 21, 57, 57],
       [85, 48, 51, 41, 69, 14, 53, 59, 96],
       [ 7, 52, 59,  4, 67,  5, 95, 93, 46]])

In [148]:
np.sort(rand_array7)

array([[23, 45, 52, 59, 62, 92, 94, 96, 98],
       [17, 24, 31, 32, 53, 66, 84, 86, 94],
       [22, 23, 31, 45, 46, 57, 65, 66, 85],
       [ 1,  8, 16, 26, 32, 38, 42, 47, 89],
       [12, 23, 24, 25, 41, 49, 59, 92, 98],
       [ 6,  7, 13, 15, 19, 35, 44, 56, 64],
       [14, 31, 62, 65, 75, 86, 86, 91, 97],
       [21, 24, 50, 57, 57, 57, 61, 62, 85],
       [14, 41, 48, 51, 53, 59, 69, 85, 96],
       [ 4,  5,  7, 46, 52, 59, 67, 93, 95]])

In [149]:
np.argsort(rand_array7)

array([[0, 2, 3, 6, 8, 1, 4, 7, 5],
       [5, 6, 1, 3, 8, 4, 0, 2, 7],
       [7, 3, 4, 2, 5, 0, 8, 1, 6],
       [1, 5, 3, 0, 4, 8, 6, 7, 2],
       [7, 6, 5, 2, 1, 4, 8, 0, 3],
       [0, 6, 8, 7, 4, 2, 3, 1, 5],
       [2, 6, 8, 5, 0, 1, 7, 3, 4],
       [6, 2, 1, 3, 7, 8, 5, 4, 0],
       [5, 3, 1, 2, 6, 7, 4, 0, 8],
       [3, 5, 0, 8, 1, 2, 4, 7, 6]], dtype=int64)

In [154]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_array7)

5

In [158]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_array7)

28

In [160]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(rand_array7, axis=1)

array([5, 7, 6, 2, 3, 5, 4, 0, 8, 6], dtype=int64)

In [161]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(rand_array7, axis=0)

array([5, 3, 6, 9, 5, 9, 5, 4, 5], dtype=int64)

In [48]:
# Create an array of normally distributed random numbers
np.random.randn()

In [168]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.